parameters:
#    instinct_bbcode.example.class: Instinct\Bundle\BbcodeBundle\Example
    instinct_bbcode.listener.loader.class: Instinct\Bundle\BbcodeBundle\EventListener\LoaderListener
    fm_bbcode.twig.extension.class: Instinct\Bundle\BbcodeBundle\Templating\BbcodeExtension
    fm_bbcode.templating.helper.class: Instinct\Bundle\BbcodeBundle\Templating\Helper\BbcodeHelper

services:
#    instinct_bbcode.example:
#        class: %instinct_bbcode.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    instinct_bbcode.listener.loader:
        class: %instinct_bbcode.listener.loader.class%
        arguments: ["@templating.engine.twig"]
        tags:
            - { name: "kernel.event_subscriber" }