fm_bbcode:
    filter_sets:
        my_default_filter:
            locale: ru
            xhtml: true
            filters: [ default, quote, image, url, email ]
            whitelist: [ b, i, u, s, sup, sub, email, img, quote, url ]



#stfalcon_tinymce:
#    theme:
#        # Simple theme as same as default theme
#        simple:
#            mode: "none"
#            theme: "advanced"
#            plugins: "bbcode"
#            theme_advanced_buttons1: "newdocument,|,undo,redo,|,bold,italic,underline,|,link,unlink,|,blockquote"
#            theme_advanced_buttons2: "fontsizeselect,|,image,|,forecolor,|,removeformat,code,|,help"
#            theme_advanced_buttons3: ""
#            theme_advanced_buttons4: ""
#            theme_advanced_toolbar_location: "top"
#            theme_advanced_toolbar_align: "center"
#            theme_advanced_styles: ""
#            entity_encoding: "raw"
#            add_unload_trigger: false
#            remove_linebreaks: false
#            inline_styles: false
#            convert_fonts_to_spans: false
#            theme_advanced_resizing: true