fm_bbcode:
    filter_sets:
        my_default_filter:
            locale: ru
            xhtml: true
            filters: [ default, block, code, email, image, quote, text, url, video ]
            whitelist: [ b, i, u, s, sup, sub, br, hr, center, code, email, mail, image, img, quote, font, size, color, url, link, video ]
