fm_bbcode:
    filter_sets:
        my_default_filter:
            locale: ru
            xhtml: true
            filters: [ default, quote, image, url, email ]
            whitelist: [ b, i, u, s, code, sup, sub, email, img, quote, url ]
