parameters:
#    instinct_news.example.class: Instinct\Bundle\NewsBundle\Example

services:
#    instinct_news.example:
#        class: %instinct_news.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
