<?php

namespace Instinct\Bundle\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Group_Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupRepository extends EntityRepository
{
}
