parameters:
    instinct_style.html_loader.class: Instinct\Bundle\StyleBundle\EventListener\HtmlLoaderListener

services:
    instinct_style.html_loader:
        class: %instinct_style.html_loader.class%
        arguments: ["@templating.engine.twig"]
        tags:
            - { name: "kernel.event_subscriber" }