parameters:
#    instinct_menu.example.class: Instinct\Bundle\MenuBundle\Example

services:
#    instinct_menu.example:
#        class: %instinct_menu.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
