instinct_user_admin_role_index:
    pattern: /{page}
    defaults: { _controller: "InstinctUserBundle:Role:index", page: 1 }
    requirements:
        page: \d*

instinct_user_admin_role_show:
    pattern: /{id}/show
    defaults: { _controller: "InstinctUserBundle:Role:show" }
    requirements:
        id: \d+
        
instinct_user_admin_role_edit:
    pattern: /{id}/edit
    defaults: { _controller: "InstinctUserBundle:Role:edit" }
    requirements:
        id: \d+
        
instinct_user_admin_role_update:
    pattern: /{id}/update
    defaults: { _controller: "InstinctUserBundle:Role:update" }
    requirements:
        id: \d+
        _method: POST
        
instinct_user_admin_role_delete:
    pattern: /{id}/delete
    defaults: { _controller: "InstinctUserBundle:Role:delete" }
    requirements:
        id: \d+
        _method: POST
        
instinct_user_admin_role_new:
    pattern: /new
    defaults: { _controller: "InstinctUserBundle:Role:new" }
    
instinct_user_admin_role_create:
    pattern: /create
    defaults: { _controller: "InstinctUserBundle:Role:create" }
    requirements:
        _method: POST
    